"""Stub tests for src/ass_ade/a0_qk_constants/exclude_dirs.py — generated by autopoietic enhancement loop."""
from __future__ import annotations


def test_exclude_dirs_importable() -> None:
    import src.ass_ade.a0_qk_constants.exclude_dirs  # noqa: F401
