"""Stub tests for src/ass_ade/a0_qk_constants/schemas.py — generated by autopoietic enhancement loop."""
from __future__ import annotations


def test_schemas_importable() -> None:
    import src.ass_ade.a0_qk_constants.schemas  # noqa: F401
