"""Stub tests for src/ass_ade/a0_qk_constants/policy_types.py — generated by autopoietic enhancement loop."""
from __future__ import annotations


def test_policy_types_importable() -> None:
    import src.ass_ade.a0_qk_constants.policy_types  # noqa: F401
