"""Emitter parity — v1 ``API_INVENTORY.md`` port (Slice D, loop-6 DEFER #2)."""

from __future__ import annotations

from pathlib import Path
from typing import Any

import pytest

from ass_ade.a1_at_functions.api_inventory_emit import (
    build_api_inventory_markdown,
    collect_public_python_symbols,
)
from ass_ade.a3_og_features.emit_api_inventory import (
    API_INVENTORY_REPORT_NAME,
    emit_api_inventory,
)


def _write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def _make_materialized_tree(root: Path) -> None:
    """Build a minimal rebuild-like tree with two tier dirs and a root init."""
    _write(
        root / "a0_qk_constants" / "types.py",
        "\"\"\"Types for the rebuilt surface.\"\"\"\n"
        "\n"
        "PUBLIC = 1\n"
        "_PRIVATE = 2\n"
        "\n"
        "class OmegaConst:\n"
        "    value = 3\n"
        "\n"
        "class _Hidden:\n"
        "    value = 4\n",
    )
    _write(
        root / "a1_at_functions" / "helpers.py",
        "\"\"\"Helpers.\"\"\"\n"
        "\n"
        "def alpha(value: int) -> int:\n"
        "    return value\n"
        "\n"
        "def _private(value: int) -> int:\n"
        "    return value\n"
        "\n"
        "async def beta(value: int) -> int:\n"
        "    return value\n",
    )
    # Noise files that should be ignored: private-name tiers, non-.py files.
    _write(root / "a1_at_functions" / "__init__.py", "")
    _write(root / "a0_qk_constants" / "__init__.py", "")
    _write(root / "a1_at_functions" / "NOTES.txt", "ignored")
    _write(root / "__init__.py", "\"\"\"package root.\"\"\"\n\ndef root_api():\n    return 1\n")


EXPECTED_MARKDOWN = (
    "# API Inventory\n"
    "\n"
    "Auto-generated by ASS-ADE rebuild packaging. This file indexes the\n"
    "materialized public Python surface so rebuilt outputs always ship a\n"
    "complete reader-facing symbol map, even before any hand-written docs\n"
    "or LLM refinement are added.\n"
    "\n"
    "- Indexed files: 3\n"
    "- Public symbols: 4\n"
    "\n"
    "## `__init__.py`\n"
    "\n"
    "- **function** `root_api`\n"
    "\n"
    "## `a0_qk_constants/types.py`\n"
    "\n"
    "- **class** `OmegaConst`\n"
    "\n"
    "## `a1_at_functions/helpers.py`\n"
    "\n"
    "- **function** `alpha`\n"
    "- **function** `beta`\n"
)


@pytest.mark.usecase
def test_collect_public_python_symbols_is_deterministic(tmp_path: Path) -> None:
    _make_materialized_tree(tmp_path)
    a = collect_public_python_symbols(tmp_path)
    b = collect_public_python_symbols(tmp_path)
    assert a == b
    names = [s["name"] for s in a]
    assert names == ["root_api", "OmegaConst", "alpha", "beta"]
    assert all(not s["name"].startswith("_") for s in a)


@pytest.mark.usecase
def test_build_api_inventory_markdown_matches_v1_format(tmp_path: Path) -> None:
    _make_materialized_tree(tmp_path)
    symbols = collect_public_python_symbols(tmp_path)
    text = build_api_inventory_markdown(symbols)
    assert text == EXPECTED_MARKDOWN


@pytest.mark.usecase
def test_build_api_inventory_markdown_empty_case() -> None:
    symbols: list[dict[str, Any]] = []
    text = build_api_inventory_markdown(symbols)
    assert "_No public Python symbols were detected._" in text
    assert "- Indexed files: 0" in text
    assert "- Public symbols: 0" in text


@pytest.mark.usecase
def test_emit_api_inventory_writes_file(tmp_path: Path) -> None:
    _make_materialized_tree(tmp_path)
    written = emit_api_inventory(tmp_path)
    assert written == tmp_path / API_INVENTORY_REPORT_NAME
    assert written.read_text(encoding="utf-8") == EXPECTED_MARKDOWN


@pytest.mark.usecase
def test_emit_api_inventory_honors_custom_out_path(tmp_path: Path) -> None:
    _make_materialized_tree(tmp_path)
    out = tmp_path / "docs" / "api.md"
    written = emit_api_inventory(tmp_path, out_path=out)
    assert written == out
    assert out.read_text(encoding="utf-8") == EXPECTED_MARKDOWN
