"""Stub tests for src/ass_ade/a0_qk_constants/cherry_types.py — generated by autopoietic enhancement loop."""
from __future__ import annotations


def test_cherry_types_importable() -> None:
    import src.ass_ade.a0_qk_constants.cherry_types  # noqa: F401
