"""Stub tests for src/ass_ade/agent/atlas.py — generated by autopoietic enhancement loop."""
from __future__ import annotations


def test_atlas_importable() -> None:
    import src.ass_ade.agent.atlas  # noqa: F401
