"""Stub tests for src/ass_ade/a0_qk_constants/reference_roots.py — generated by autopoietic enhancement loop."""
from __future__ import annotations


def test_reference_roots_importable() -> None:
    import src.ass_ade.a0_qk_constants.reference_roots  # noqa: F401
