"""Stub tests for src/ass_ade/a0_qk_constants/tier_names.py — generated by autopoietic enhancement loop."""
from __future__ import annotations


def test_tier_names_importable() -> None:
    import src.ass_ade.a0_qk_constants.tier_names  # noqa: F401
