# Extracted from C:/!ass-ade-evoMERGE-g3-20260419-003649/a1_at_functions/at_draft_render_evolution_markdown.py:7
# Component id: at.source.a1_at_functions.render_evolution_markdown
from __future__ import annotations

__version__ = "0.1.0"

def render_evolution_markdown(root: Path, events: list[EvolutionEvent] | None = None) -> str:
    root = root.resolve()
    events = events if events is not None else _load_ledger(root)
    current_version = read_project_version(root)
    git = collect_git_state(root)
    lines = [
        "# ASS-ADE Evolution Ledger",
        "",
        "This file is generated by `ass-ade protocol evolution-record` and related protocol commands.",
        "It records public-safe decision summaries, command receipts, metrics, and artifact paths.",
        "It does not store secrets or private chain-of-thought.",
        "",
        "## Current State",
        "",
        f"- Version: {current_version}",
        f"- Git branch: {git.branch if git.available else 'unavailable'}",
        f"- Git commit: {git.commit if git.available else 'unavailable'}",
        f"- Dirty worktree: {git.dirty if git.available else 'unknown'}",
        "",
        "## Events",
        "",
    ]
    if not events:
        lines.append("No evolution events have been recorded yet.")
        return "\n".join(lines)

    for event in sorted(events, key=lambda item: item.timestamp_utc, reverse=True):
        lines.extend(
            [
                f"### {event.timestamp_utc} - {event.event_type}",
                "",
                f"- Event ID: `{event.event_id}`",
                f"- Version: {event.version}",
                f"- Summary: {event.summary}",
            ]
        )
        if event.rationale:
            lines.append(f"- Rationale: {event.rationale}")
        if event.git.available:
            lines.append(
                f"- Git: `{event.git.branch}` at `{event.git.commit}` "
                f"(dirty={event.git.dirty}, staged={event.git.staged}, "
                f"unstaged={event.git.unstaged}, untracked={event.git.untracked})"
            )
        if event.commands:
            lines.extend(["", "Commands:"])
            for command in event.commands:
                note = f" - {command.notes}" if command.notes else ""
                lines.append(f"- [{command.status}] `{command.command}`{note}")
        if event.metrics:
            lines.extend(["", "Metrics:"])
            for key, value in sorted(event.metrics.items()):
                lines.append(f"- `{key}`: {value}")
        if event.rebuild:
            lines.extend(["", "Rebuild:"])
            for key, value in sorted(event.rebuild.items()):
                if key == "certificate":
                    continue
                lines.append(f"- `{key}`: {value}")
            cert = event.rebuild.get("certificate")
            if isinstance(cert, dict):
                sha = cert.get("certificate_sha256") or cert.get("certificate_hash") or cert.get("sha256")
                if sha:
                    lines.append(f"- `certificate_sha256`: {sha}")
        if event.reports:
            lines.extend(["", "Reports:"])
            lines.extend(f"- `{_display_path(root, item)}`" for item in event.reports)
        if event.artifacts:
            lines.extend(["", "Artifacts:"])
            lines.extend(f"- `{_display_path(root, item)}`" for item in event.artifacts)
        if event.next_steps:
            lines.extend(["", "Next Steps:"])
            lines.extend(f"- {item}" for item in event.next_steps)
        if event.lineage_ids:
            lines.extend(["", f"Lineage receipts: {len(event.lineage_ids)}"])
        lines.append("")
    return "\n".join(lines).rstrip()
