# Extracted from C:/!ass-ade/tests/test_cli.py:197
# Component id: at.source.ass_ade.test_rebuild_preserves_existing_showcase_readme
from __future__ import annotations

__version__ = "0.1.0"

def test_rebuild_preserves_existing_showcase_readme(tmp_path: Path) -> None:
    src = tmp_path / "proj"
    src.mkdir()
    (src / "util.py").write_text("def add(a, b): return a + b\n", encoding="utf-8")
    out = tmp_path / "proj-out"
    out.mkdir()
    showcase = b"# Showcase README\r\n\r\nKeep the hand-authored public page.\r\n"
    (out / "README.md").write_bytes(showcase)

    result = runner.invoke(app, ["rebuild", str(src), str(out), "--yes", "--no-certify", "--json"])

    assert result.exit_code == 0
    assert (out / "README.md").read_bytes() == showcase
    generated = (out / "0_README.md").read_text(encoding="utf-8")
    assert "Auto-generated by ASS-ADE rebuild engine" in generated
