"""Tier a1 — pure helpers that build ``API_INVENTORY.md`` from a materialized tree.

Ported from ``ass_ade.engine.rebuild.coverage_emitter`` (v1). The v1 function was
an internal private helper buried inside the larger coverage emitter; the v1.1
port keeps the **same deterministic output format** (sorted by file → kind →
name) so golden diff is possible across versions.
"""

from __future__ import annotations

import ast
from collections import defaultdict
from pathlib import Path
from typing import Any

# Tier directories that are scanned when present (mirrors v1 behavior).
_TIER_NAMES: tuple[str, ...] = (
    "a0_qk_constants",
    "a1_at_functions",
    "a2_mo_composites",
    "a3_og_features",
    "a4_sy_orchestration",
)


def _relative(root: Path, path: Path) -> str:
    return path.resolve().relative_to(root.resolve()).as_posix()


def _source_dirs(target_root: Path) -> list[Path]:
    dirs: list[Path] = []
    for tier in _TIER_NAMES:
        tier_dir = target_root / tier
        if tier_dir.is_dir():
            dirs.append(tier_dir)
    return dirs


def _source_python_files(target_root: Path) -> list[Path]:
    files: list[Path] = []
    for directory in _source_dirs(target_root):
        files.extend(path for path in directory.rglob("*.py") if path.is_file())
    root_init = target_root / "__init__.py"
    if root_init.is_file():
        files.append(root_init)
    return sorted({path.resolve() for path in files})


def collect_public_python_symbols(target_root: Path) -> list[dict[str, Any]]:
    """Return deterministic list of public (non-underscore) classes + functions.

    Each entry: ``{"file": <posix-rel>, "kind": "class"|"function", "name": str}``.
    Result is sorted by ``(file, kind, name)``.
    """
    symbols: list[dict[str, Any]] = []
    for path in _source_python_files(target_root):
        try:
            source = path.read_text(encoding="utf-8", errors="replace")
            tree = ast.parse(source, filename=str(path))
        except (OSError, SyntaxError):
            continue
        rel = _relative(target_root, path)
        for node in ast.walk(tree):
            if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
                continue
            if node.name.startswith("_"):
                continue
            kind = "class" if isinstance(node, ast.ClassDef) else "function"
            symbols.append({"file": rel, "kind": kind, "name": node.name})
    symbols.sort(key=lambda item: (item["file"], item["kind"], item["name"]))
    return symbols


def build_api_inventory_markdown(symbols: list[dict[str, Any]]) -> str:
    """Return the same ``API_INVENTORY.md`` text v1 emits (byte-for-byte)."""
    grouped: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for symbol in symbols:
        grouped[symbol["file"]].append(symbol)

    lines = [
        "# API Inventory",
        "",
        "Auto-generated by ASS-ADE rebuild packaging. This file indexes the",
        "materialized public Python surface so rebuilt outputs always ship a",
        "complete reader-facing symbol map, even before any hand-written docs",
        "or LLM refinement are added.",
        "",
        f"- Indexed files: {len(grouped)}",
        f"- Public symbols: {len(symbols)}",
        "",
    ]

    if not grouped:
        lines.append("_No public Python symbols were detected._")
        lines.append("")
        return "\n".join(lines)

    for filepath, entries in sorted(grouped.items()):
        lines.extend([f"## `{filepath}`", ""])
        for entry in entries:
            lines.append(f"- **{entry['kind']}** `{entry['name']}`")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"
