"""Schema version strings for interchange with downstream tooling."""

INGESTION_SCHEMA = "ASSADE-SPEC-005-V11"
GAP_FILL_SCHEMA = "ASSADE-SPEC-005-V11"
COMPONENT_SCHEMA_V11 = "ASSADE-SPEC-003-V11"
REGISTRY_SNAPSHOT_SCHEMA = "ASSADE-REG-SNAPSHOT-V11"
ASSIMILATION_LOG_SCHEMA = "ASSADE-ASSIMILATION-V11"
